Unit test
Dekz120/server_eventloop pull request #5
Opened 2022-11-10 16:31 UTC by Dekz120

2022-11-10 17:25 UTC, Yanpas requested changes

2022-11-10 17:25 UTC, Yanpas commented on elooplib/client.hpp
> +        NotExitsts
Not exists. Better `Unknown`

2022-11-10 17:25 UTC, Yanpas commented on elooplib/client.hpp
> +    std::string m_arg;
Prefixing members with m is my team's codestyle, please fix

2022-11-10 17:25 UTC, Yanpas commented on test/cmd_parser/command_parser.cpp
> +TEST_CASE("Command parser test")
Create two cases: Invalid commands and valid commands

2022-11-10 17:25 UTC, Yanpas commented on test/file_cmd/file_cmd.cpp
> +TEST_CASE("Compression test") {
Good test!

2022-11-10 17:25 UTC, Yanpas commented on .github/workflows/make_check.yml
> +
You can also add building and running unit tests to Github-CI

2022-11-10 17:25 UTC, Yanpas commented on test/Makefile
> +CXXFLAGS = -std=c++2a
You can call this malefile from the top one using: `$(MAKE) -C test`

2022-11-10 19:59 UTC, Dekz120 commented on elooplib/client.hpp
> +        NotExitsts
मेरी अंग्रेजी के लिए खेद है

2022-11-22 22:39 UTC, Yanpas approved these changes

2022-11-22 22:39 UTC, Yanpas commented on test/cmd_parser/command_parser.cpp
> +TEST_CASE("Vaild command parser test")
Valid

2022-11-22 22:40 UTC, Yanpas commented
You have two identical CI jobs, don't you?

2022-11-23 09:32 UTC, Dekz120 commented on test/cmd_parser/command_parser.cpp
> +TEST_CASE("Vaild command parser test")
Wild♂

2022-12-04 15:11 UTC, Yanpas commented
Ping

2022-12-05 10:38 UTC, Dekz120 commented
> You have two identical CI jobs, don't you?

fixed in commit. but i have to resolve conlfict(in CI) before merge

2022-12-05 10:48 UTC, Yanpas approved these changes

2022-12-05 11:05 UTC, merged